### ISSUE TITLE
Options Glitch in Main Menu

### ISSUE THREAD

**Issue by THB0705** [8BitToaster/Grand-Expansion#11]
When I start the game, (the latest commit upload in the last 5 minutes) and open the options from there, this error is thrown.

`Traceback (most recent call last):
  File "main.py", line 997, in <module>
    MainMenu.HomeScreen(pygame, gameDisplay,[font_40,font_50,font_150], clock)
  File "\Grand-Expansion-master\Grand Expansion\MainMenu.py", line 38, in HomeScreen
    import Main
  File "\Grand-Expansion-master\Grand Expansion\Main.py", line 997, in <module>
    MainMenu.HomeScreen(pygame, gameDisplay,[font_40,font_50,font_150], clock)
  File "\Grand-Expansion-master\Grand Expansion\MainMenu.py", line 160, in HomeScreen
    if MusicPaused == False:
NameError: name 'MusicPaused' is not defined`

**Comment by THB0705** [comment]
This issue may have been resolved in the last update, I have not checked yet.

**Comment by 8BitToaster** [comment]
Yes sorry I see what happened. It will be fixed in the next upload. I keep seeing little bugs that I didn't see when I was playtesting it because I wanted to get out this version because I can't for another 3 hours.

**Comment by 8BitToaster** [comment]
This is fixed. I'm sorry it happened to you.

-8BitToaster

**Comment by THB0705** [comment]
You don't have to apologize ;).
