### ISSUE TITLE
Icons on Mac

### ISSUE THREAD

**Issue by 8BitToaster** [8BitToaster/Grand-Expansion#16]
So what I used to program this code and what I plan I using the whole time is a Macbook. This means that if I want to make a shortcut(called alias on Macs) I can't make a custom icon for them. Even if I did somehow figure that out I don't think it would work on windows which more people use. I'm not exactly sure what to do on this, but it would be nice if someone knew about it. There are some modules that can make it into an executable for everyone, but I would have to look into that. Thanks for all the help(Especially THB0705).

-8BitToaster

**Comment by THB0705** [comment]
Something I would do by default, is on start up, gather a user's screen size, operating system, miscellaneous information like this. For example using the operating system check, you can do depending on the outcome do different things that are OS specific (e.g. setting the icons, for windows you would set it but then for mac you would not set it until you found a solution).

For the creating executables, if you're using python 3.7, right now there are not many properly working options. Myself, I have been struggling with this, but I heard cx_freeze is coming close to working properly.
