### ISSUE TITLE
Key Usage

### ISSUE THREAD

**Issue by THB0705** [8BitToaster/Grand-Expansion#18]
Suggestion: Allow the player to move the selected tile using the WASD and arrow keys. This would be a great improvement especially for larger maps when wanting to upgrade things quickly. Having to move the mouse so much can be tiresome.

This may be tricky to implement, if you have any questions let me know. I alsp understand if that is going to be too much work for this game. Consider then using keys in your next game ;)

**Comment by 8BitToaster** [comment]
This won't be that hard to implement. Thanks for the idea! If you're wondering how I could do it all I have to do is see what tile I'm selecting and use the keys to move it.

-8BitToaster
