### ISSUE TITLE
Saving Feature; Importing and Exporting

### ISSUE THREAD

**Issue by THB0705** [8BitToaster/Grand-Expansion#7]
Consider this suggestion regardless of whether you have added encryption to your import or export functions.

- Add a file with whatever name you like to your files in the project, just a text file. Let's call it save.txt .

- Add a save button in the options menu or somewhere in-game. If this save button is clicked, the saveFunction is called. The saveFunction then calls on the export function and instead of writing the gamestate to the console it writes it to save.txt .

- In the main menu, use the left button to create a button called load game. When clicked this calls the load game function which then calls an altered version of the import function but then instead of expecting console input, it just checks whether there is any saved game at all by trying to read the save.txt file. If this fails, the button does nothing, the user apparently has never played the game before. If it works, well then the game is started in the previous game state in which the player was left of.

This would be a nice complementary to the import and export functions where the user has to go through the hussle of copying long strands of text, etc.. What do you think? Should be doable right?

**Comment by THB0705** [comment]
I would keep the import/export function but make them a bit more obscure. (smaller buttons?) Keep them as long as there is no multiple save option.

**Comment by 8BitToaster** [comment]
The new version is added for autosaving every 30 seconds and also you can now save ingame manually. The import/export is still there, but you don't have to use them anymore.

-8BitToaster
